"""added feed uid

Revision ID: 711ca6ee4308
Revises: 9ffc19ba575e
Create Date: 2021-01-29 23:08:03.545265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '711ca6ee4308'
down_revision = '9ffc19ba575e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed', sa.Column('uid', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_feed_uid'), 'feed', ['uid'], unique=True)
    op.add_column('like', sa.Column('uid', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_like_uid'), 'like', ['uid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_like_uid'), table_name='like')
    op.drop_column('like', 'uid')
    op.drop_index(op.f('ix_feed_uid'), table_name='feed')
    op.drop_column('feed', 'uid')
    # ### end Alembic commands ###
