"""added default timestamp to updated

Revision ID: 88da0cf89e7a
Revises: fbb6c3db4b6f
Create Date: 2020-08-21 21:36:34.786488

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '88da0cf89e7a'
down_revision = 'fbb6c3db4b6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed', sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('post', 'updated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('updated', mysql.DATETIME(), nullable=True))
    op.drop_column('feed', 'updated')
    # ### end Alembic commands ###
