"""added default timestamp to updated post

Revision ID: 9ffc19ba575e
Revises: 88da0cf89e7a
Create Date: 2020-08-21 21:37:35.756450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ffc19ba575e'
down_revision = '88da0cf89e7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'updated')
    # ### end Alembic commands ###
